/**
 * Smoke test: validates Docker compose stack health and basic API behavior.
 * Run via: npx tsx scripts/smoke-test.ts
 */
import { spawn } from 'child_process';
const API_BASE = 'http://localhost:3001/api';
const WEB_BASE = 'http://localhost:5173';
const QDRANT_BASE = 'http://localhost:6333';
const TIMEOUT_MS = 120_000;
const POLL_INTERVAL_MS = 2_000;
function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}
async function healthCheck(url, expectOk = true) {
    try {
        const res = await fetch(url, { signal: AbortSignal.timeout(5_000) });
        return expectOk ? res.ok : true;
    }
    catch {
        return false;
    }
}
async function waitForService(name, url, expectOk = true) {
    const start = Date.now();
    while (Date.now() - start < TIMEOUT_MS) {
        if (await healthCheck(url, expectOk)) {
            console.log(`✅ ${name} is healthy`);
            return;
        }
        console.log(`⏳ Waiting for ${name}...`);
        await sleep(POLL_INTERVAL_MS);
    }
    throw new Error(`${name} failed to become healthy within ${TIMEOUT_MS}ms`);
}
async function runDockerCompose() {
    console.log('🐳 Starting docker compose...');
    return new Promise((resolve, reject) => {
        const proc = spawn('docker', ['compose', 'up', '-d'], { stdio: 'inherit', shell: true });
        proc.on('close', (code) => {
            if (code === 0)
                resolve();
            else
                reject(new Error(`docker compose up exited with ${code}`));
        });
    });
}
async function stopDockerCompose() {
    console.log('🧹 Stopping docker compose...');
    return new Promise((resolve) => {
        const proc = spawn('docker', ['compose', 'down'], { stdio: 'inherit', shell: true });
        proc.on('close', () => resolve());
    });
}
async function apiSmoke() {
    // Health
    const health = await fetch(`${API_BASE}/health`).then((r) => r.json());
    console.log('Health:', health);
    // Worlds
    const worlds = await fetch(`${API_BASE}/worlds`).then((r) => r.json());
    console.log(`Worlds count: ${worlds.data?.length ?? 0}`);
    // Create world
    const createRes = await fetch(`${API_BASE}/worlds`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: 'Smoke Test World', description: 'Auto-generated by smoke test' }),
    }).then((r) => r.json());
    console.log('Created world:', createRes.data?.id);
    // Characters
    const chars = await fetch(`${API_BASE}/characters?worldId=${createRes.data.id}`).then((r) => r.json());
    console.log(`Characters count: ${chars.data?.length ?? 0}`);
    // Lore
    const lore = await fetch(`${API_BASE}/lore?worldId=${createRes.data.id}`).then((r) => r.json());
    console.log(`Lore count: ${lore.data?.length ?? 0}`);
    // Chat
    const chat = await fetch(`${API_BASE}/chat/character/1`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: 'Hello from smoke test' }),
    }).then((r) => r.json());
    console.log('Chat response present:', !!chat.data?.response || !!chat.response);
    return createRes.data;
}
async function main() {
    let failed = false;
    try {
        await runDockerCompose();
        await waitForService('Postgres', `${API_BASE}/health`); // API depends on postgres
        await waitForService('Qdrant', `${QDRANT_BASE}/collections`);
        await waitForService('API', `${API_BASE}/health`);
        await waitForService('Web', WEB_BASE, false);
        const world = await apiSmoke();
        // Cleanup created world
        await fetch(`${API_BASE}/worlds/${world.id}`, { method: 'DELETE' });
        console.log(`🗑️ Cleaned up world ${world.id}`);
        console.log('\n✅ Smoke test passed');
    }
    catch (err) {
        failed = true;
        console.error('\n❌ Smoke test failed:', err instanceof Error ? err.message : String(err));
    }
    finally {
        await stopDockerCompose();
    }
    process.exit(failed ? 1 : 0);
}
main();
//# sourceMappingURL=smoke-test.js.map